### ISSUE TITLE
newpct new icon

### ISSUE THREAD

**Issue by Greenbaburu** [mancuniancol/script.quasar.newpct1-mc#1]
if you like it...
![newpct1](https://cloud.githubusercontent.com/assets/8045152/13459831/bedec298-e076-11e5-8518-663155c03d8f.jpg)
![newpct1](https://cloud.githubusercontent.com/assets/8045152/13459832/c08aa2ce-e076-11e5-914f-2590f6551dd7.png)

**Comment by mancuniancol** [comment]
Wow, yes of course. Thank so much

**Comment by Greenbaburu** [comment]
Thanks to you!
